# Generated by Django 5.1.6 on 2025-06-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_tiendas_alter_direccionenvio_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retiro_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.tiendas'),
        ),
    ]
