# Generated by Django 5.1.6 on 2025-04-24 19:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1995, 8, 15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.paises'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
