# Generated by Django 5.1.6 on 2025-05-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.paises'),
        ),
    ]
