# Generated by Django 5.1.6 on 2025-05-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Paises',
        ),
    ]
