# Generated by Django 5.1.6 on 2025-05-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_customuser_pais_delete_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod_area',
            field=models.CharField(choices=[('+5411', 'Buenos Aires (CABA)'), ('+54221', 'La Plata'), ('+54351', 'Córdoba Capital'), ('+54381', 'Tucumán'), ('+54387', 'Salta'), ('+54383', 'Jujuy'), ('+54371', 'San Luis'), ('+54261', 'Mendoza'), ('+54340', 'Catamarca'), ('+54385', 'Santiago del Estero'), ('+54343', 'Entre Ríos (Paraná)'), ('+54364', 'San Juan'), ('+54384', 'La Rioja'), ('+54375', 'Formosa'), ('+54372', 'Chaco (Resistencia)'), ('+54294', 'Santa Cruz (Río Gallegos)'), ('+54296', 'Tierra del Fuego'), ('+54329', 'Neuquén'), ('+54387', 'Salta'), ('+54386', 'Orán'), ('+54342', 'Santa Fe')], default='+5411', max_length=7),
        ),
    ]
