# Generated by Django 5.1.6 on 2025-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_customuser_cod_area_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cod_area',
            field=models.CharField(choices=[('+54 11', 'Buenos Aires (+54 11)'), ('+54 221', 'La Plata (+54 211)'), ('+54 351', 'Córdoba Capital (+54 351)'), ('+54 381', 'Tucumán (+54 381)'), ('+54 387', 'Salta (+54 387)'), ('+54 383', 'Jujuy (+54 383)'), ('+54 371', 'San Luis (+54 371)'), ('+54 261', 'Mendoza (+54 261)'), ('+54 340', 'Catamarca (+54 340)'), ('+54 385', 'Santiago del Estero (+54 385)'), ('+54 343', 'Entre Ríos (+54 343)'), ('+54 364', 'San Juan (+54 364)'), ('+54 384', 'La Rioja (+54 384)'), ('+54 375', 'Formosa (+54 375)'), ('+54 372', 'Chaco (+54 372)'), ('+54 294', 'Santa Cruz (+54 294)'), ('+54 296', 'Tierra del Fuego (+54 296)'), ('+54 329', 'Neuquén (+54 329)'), ('+54 386', 'Orán (+54 386)'), ('+54 342', 'Santa Fe (+54 342)')], max_length=7),
        ),
    ]
