# Generated by Django 5.1.6 on 2025-04-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoConImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes_secundarias/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_secundarias', to='tienda.productoconimagen')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.modelo'),
        ),
        migrations.CreateModel(
            name='AccesoriosPC',
            fields=[
                ('productoconimagen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.productoconimagen')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('compatibilidad', models.CharField(max_length=100)),
                ('inalambrico', models.BooleanField(default=False)),
                ('tiempo_bateria', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('puertos', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelo')),
                ('tipo_accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tipoaccesorio')),
            ],
            options={
                'abstract': False,
            },
            bases=('tienda.productoconimagen', models.Model),
        ),
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('productoconimagen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.productoconimagen')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('almacenamiento', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('pantalla', models.CharField(max_length=100)),
                ('camara', models.CharField(max_length=100)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelo')),
            ],
            options={
                'abstract': False,
            },
            bases=('tienda.productoconimagen', models.Model),
        ),
        migrations.CreateModel(
            name='Consolas',
            fields=[
                ('productoconimagen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.productoconimagen')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('edicion', models.CharField(blank=True, max_length=50, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('cant_controles', models.PositiveIntegerField()),
                ('peso', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelo')),
            ],
            options={
                'abstract': False,
            },
            bases=('tienda.productoconimagen', models.Model),
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('productoconimagen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.productoconimagen')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('edicion', models.CharField(default='Standar', max_length=50)),
                ('tamaño_juego', models.CharField(max_length=30)),
                ('clasificacion_edad', models.CharField(choices=[('E', 'Everyone (E)'), ('E10', 'Everyone 10+ (E10+)'), ('T', 'Teen (T)'), ('M', 'Mature (M)'), ('A', 'Adults Only (AO)')], max_length=4)),
                ('formato', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], max_length=10)),
                ('generos', models.ManyToManyField(to='tienda.genero')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelo')),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.plataforma')),
            ],
            options={
                'abstract': False,
            },
            bases=('tienda.productoconimagen', models.Model),
        ),
        migrations.CreateModel(
            name='RelojInteligentes',
            fields=[
                ('productoconimagen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.productoconimagen')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('tipo_pantalla', models.CharField(max_length=50)),
                ('duracion_bateria', models.CharField(max_length=50)),
                ('conectividad', models.CharField(max_length=100)),
                ('compatibilidad', models.CharField(max_length=100)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelo')),
            ],
            options={
                'abstract': False,
            },
            bases=('tienda.productoconimagen', models.Model),
        ),
    ]
