# Generated by Django 5.1.6 on 2025-04-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='modelo',
        ),
        migrations.AddField(
            model_name='marca',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
            preserve_default=False,
        ),
    ]
