# Generated by Django 5.1.6 on 2025-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_empresa_marca_remove_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoaccesorio',
            name='sub_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tipoaccesorio',
            name='tipo',
            field=models.CharField(choices=[('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('ALTAVOZ', 'Altavoz'), ('AURICULAR', 'Auricular'), ('MICROFONO', 'Micrófono'), ('CAMARA', 'Cámara')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
