# Generated by Django 5.1.6 on 2025-04-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_tipoaccesorio_sub_tipo_tipoaccesorio_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesoriospc',
            old_name='tipo_accesorio',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='tipoaccesorio',
            name='sub_tipo',
        ),
        migrations.RemoveField(
            model_name='tipoaccesorio',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tipoaccesorio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='SubTipoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='tienda.tipoaccesorio')),
            ],
        ),
        migrations.AddField(
            model_name='accesoriospc',
            name='subtipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.subtipoaccesorio'),
            preserve_default=False,
        ),
    ]
