# Generated by Django 5.1.6 on 2025-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_tipo_accesorio_accesoriospc_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoriospc',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='celulares',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='consolas',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='relojinteligentes',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
