# Generated by Django 5.1.6 on 2025-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_accesoriospc_precio_alter_celulares_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='duracion_bateria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consolas',
            name='cant_controles',
            field=models.CharField(max_length=50),
        ),
    ]
