# Generated by Django 5.1.6 on 2025-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_consolas_duracion_bateria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='juegos_incluidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
