# Generated by Django 5.1.6 on 2025-04-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_consolas_juegos_incluidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celulares',
            old_name='camara',
            new_name='resolucion_cam_frontal',
        ),
        migrations.AddField(
            model_name='celulares',
            name='procesador',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celulares',
            name='resolucion_cam_trasera',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
