# Generated by Django 5.1.6 on 2025-04-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_rename_camara_celulares_resolucion_cam_frontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relojinteligentes',
            name='sensores',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relojinteligentes',
            name='tamaño_pantalla',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
