# Generated by Django 5.1.6 on 2025-04-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_relojinteligentes_sensores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='accesoriospc',
            name='subtipo',
        ),
        migrations.AlterField(
            model_name='accesoriospc',
            name='tipo',
            field=models.CharField(choices=[('teclado', 'Teclado'), ('mouse', 'Mouse'), ('altavoz', 'Altavoz'), ('microfono', 'Micrófono'), ('auricular', 'Auricular'), ('camara', 'Cámara')], max_length=30),
        ),
        migrations.RenameField(
            model_name='accesoriospc',
            old_name='puertos',
            new_name='resolucion',
        ),
        migrations.AddField(
            model_name='accesoriospc',
            name='bateria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesoriospc',
            name='microfono_integrado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesoriospc',
            name='rgb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesoriospc',
            name='peso',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juegos',
            name='formato',
            field=models.CharField(choices=[('FISICO', 'Físico')], max_length=10),
        ),
        migrations.AddField(
            model_name='accesoriospc',
            name='conexiones',
            field=models.ManyToManyField(to='tienda.conexion'),
        ),
        migrations.DeleteModel(
            name='SubTipoAccesorio',
        ),
        migrations.DeleteModel(
            name='TipoAccesorio',
        ),
    ]
