# Generated by Django 5.1.6 on 2025-05-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_conexion_remove_accesoriospc_subtipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relojinteligentes',
            name='duracion_bateria',
            field=models.CharField(max_length=100),
        ),
    ]
