# Generated by Django 5.1.6 on 2025-07-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_relojinteligentes_duracion_bateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
