# Generated by Django 5.1.6 on 2025-07-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_empresa_logo_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo_empresa',
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_marca',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
